version: '3.3'

services:


  ## MySQL Docker Compose Config for Customer services
  mysql-1:
    image:  mysql:8.0
    container_name: mysql-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db1
    ports:
      - "3306:3306"
    expose:
      - "3306"

  mysql-2:
    image: mysql:8.0
    container_name: mysql-2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db2
    ports:
      - "3307:3306"
    expose:
      - "3307"
